//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        public int IdAsiento { get; set; }
        public string Descripcion { get; set; }
        public int IdCliente { get; set; }
        public string Cuenta { get; set; }
        public int IdTipoMovimiento { get; set; }
        public decimal FechaAsiento { get; set; }
        public decimal MontoAsiento { get; set; }
        public int IdEstado { get; set; }
    }
}
